# ==============================================================================
# GitHub labels
# ==============================================================================

- name: 'Type: Task'
  color: '315d9c'
  description: 'General tasks'
- name: 'Type: Feature'
  color: '315d9c'
  description: 'New feature that does not exist yet'
- name: 'Type: Enhancement'
  color: '315d9c'
  description: 'Improvement of an already existing feature'
- name: 'Type: Bug'
  color: '315d9c'
  description: 'Something does not seem to be working as expected'
- name: 'Type: Discussion'
  color: '315d9c'
  description: 'Not an issue'

- name: 'Resolution: Done'
  color: '5f6858'
  description: 'Resolved successfully'
- name: 'Resolution: Rejected'
  color: '5f6858'
  description: 'This will not be worked on'
- name: 'Resolution: Duplicate'
  color: '5f6858'
  description: 'This is already covered elsewhere'
- name: 'Resolution: Invalid'
  color: '5f6858'
  description: 'This does not seem right'
- name: 'Resolution: Stale'
  color: '5f6858'
  description: 'This went stale'

- name: 'Scope: Root'
  color: '0e8a16'
  description: 'Refers to the monorepo root'
- name: 'Scope: Documentation'
  color: '0e8a16'
  description: 'Refers to the documentation'
- name: 'Scope: Package/reago'
  color: '0e8a16'
  description: 'Refers to the `reago` package'
- name: 'Scope: Package/reago-react'
  color: '0e8a16'
  description: 'Refers to the `reago-react` package'
- name: 'Scope: Package/eslint-plugin-reago'
  color: '0e8a16'
  description: 'Refers to the `eslint-plugin-reago` package'
