# ==============================================================================
# PR labeler
# ==============================================================================

'Scope: Root':
  - changed-files:
    - any-glob-to-any-file:
      - '*'
      - '.*/**'

'Scope: Documentation':
  - changed-files:
    - any-glob-to-any-file: documentation/**

'Scope: Package/reago':
  - changed-files:
    - any-glob-to-any-file: package/reago/**

'Scope: Package/reago-react':
  - changed-files:
    - any-glob-to-any-file: package/reago-react/**

'Scope: Package/eslint-plugin-reago':
  - changed-files:
    - any-glob-to-any-file: package/eslint-plugin-reago/**
