# ==============================================================================
# GitHub labels
# ==============================================================================

- name: 'type:task'
  color: '315d9c'
  description: 'General tasks'
- name: 'type:feature'
  color: '315d9c'
  description: 'New feature that does not exist yet'
- name: 'type:enhancement'
  color: '315d9c'
  description: 'Improvement of an already existing feature'
- name: 'type:bug'
  color: '315d9c'
  description: 'Something does not seem to be working as expected'
- name: 'type:discussion'
  color: '315d9c'
  description: 'Not an issue'

- name: 'resolution:done'
  color: '5f6858'
  description: 'Resolved successfully'
- name: 'resolution:rejected'
  color: '5f6858'
  description: 'This will not be worked on'
- name: 'resolution:duplicate'
  color: '5f6858'
  description: 'This is already covered elsewhere'
- name: 'resolution:invalid'
  color: '5f6858'
  description: 'This does not seem right'
- name: 'resolution:stale'
  color: '5f6858'
  description: 'This went stale'

- name: 'scope:meta'
  color: '0e8a16'
  description: 'Refers to the monorepo setup'
- name: 'scope:changeset'
  color: '0e8a16'
  description: 'Refers to the changeset'
- name: 'scope:documentation'
  color: '0e8a16'
  description: 'Refers to the documentation'
- name: 'scope:package/reago'
  color: '0e8a16'
  description: 'Refers to the `reago` package'
- name: 'scope:package/reago-react'
  color: '0e8a16'
  description: 'Refers to the `reago-react` package'
- name: 'scope:package/eslint-plugin-reago'
  color: '0e8a16'
  description: 'Refers to the `eslint-plugin-reago` package'
