# ==============================================================================
# PR labeler
# ==============================================================================

'scope:meta':
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '*'
      - '.*/**'
      - 'script/**'
    - all-globs-to-all-files:
      - '!*.md'
      - '!.changeset/*.md'

'scope:changeset':
- changed-files:
  - any-glob-to-any-file:
    - '.changeset/*.md'

'scope:documentation':
- changed-files:
  - any-glob-to-any-file:
    - '*.md'
    - 'package/*/src/*.md'
    - 'documentation/**'

'scope:package/reago':
- changed-files:
  - any-glob-to-any-file: 'package/reago/**'

'scope:package/reago-react':
- changed-files:
  - any-glob-to-any-file: 'package/reago-react/**'

'scope:package/eslint-plugin-reago':
- changed-files:
  - any-glob-to-any-file: 'package/eslint-plugin-reago/**'
