# ==============================================================================
# Codecov configuration
# ==============================================================================

coverage:
  status:
    project:
      default:
        informational: true
    patch: off

comment:
  layout: 'diff, files'
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

github_checks:
  annotations: false
