# ==============================================================================
# Bug report
# ==============================================================================

name: Report a bug
description: Please report software bugs here. Is there something not working as expected?
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Hey there! 👋

        Thank you for taking the time to report this bug. Your input helps make this project better.

        Before you proceed:
        - This template is used **only for reporting bugs**.
        - Before opening a new issue, please do a [search](https://github.com/areven/reago/issues) of existing issues and upvote the existing issue instead.
        - For issues of a different nature, please consider posting in [Discussions](https://github.com/areven/reago/discussions) or selecting a more suitable category.

        Need help with your own project? There are options too:
        - Start a discussion in the [Q&A](https://github.com/areven/reago/discussions/categories/q-a) section.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Tell us, what is not working as expected?
      placeholder: >
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: reproduction-code
    attributes:
      label: Reproduction code
      description: (Optional) If possible, please provide a reproduction code, ideally in the form of a test case.
      placeholder: |
        test('issue reproduction', () => {
          ...
        });
    validations:
      required: false
