# ==============================================================================
# Changeset
# ==============================================================================
# This workflow publishes packages and manages changesets

name: Changeset
on:
  push:
    branches:
      - main

env:
  CI: true
  HUSKY: 0

permissions:
  contents: write
  packages: write
  pull-requests: write

concurrency:
  group: changeset/${{ github.workflow }}/${{ github.ref }}

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'areven'
    outputs:
      published: ${{ steps.flags.outputs.published }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup git user
        run: |
          git config --global user.name "Areven Bot"
          git config --global user.email "bot@areven.com"
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ci-npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ci-npm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Store the auth token
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > ".npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
      - name: Publish or create a PR
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore: release packages'
          commit: 'chore: release packages'
          publish: ./script/ci-changeset-publish.sh
          version: ./script/ci-changeset-version.sh
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set the output flags
        id: flags
        run: echo "published=${{ steps.changesets.outputs.published }}" >> "$GITHUB_OUTPUT"
  deploy-documentation:
    needs:
      - sync
    if: needs.sync.outputs.published == 'true'
    uses: ./.github/workflows/documentation-deployment.yml
    secrets: inherit
