# ==============================================================================
# Code validation
# ==============================================================================
# This workflow checks a commit for correctness

name: Code validation
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  CI: true
  HUSKY: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  precheck:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch"]'

  commitlint:
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.should_skip != 'true'
    env:
      BASH_ENV: ~/.profile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ci-npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ci-npm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
          --to ${{ github.event.pull_request.head.sha }} --verbose

  tsc:
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.should_skip != 'true'
    env:
      BASH_ENV: ~/.profile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ci-npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ci-npm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Run tsc build
        run: npx tsc --build

  vitest:
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.should_skip != 'true'
    env:
      BASH_ENV: ~/.profile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ci-npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ci-npm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx vitest run --coverage
      - name: Upload coverage stats
        if: github.repository_owner == 'areven'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
